version: '3'

services:
  database:
    build: ./database
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: domusordo
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - domusnet
    hostname: database
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./web/API
    restart: always
    networks:
      - domusnet
    depends_on:
      - database
    hostname: api

  interface:
    build: ./web/interface
    restart: always
    networks:
      - domusnet
    depends_on:
      - api
    hostname: interface

  proxy:
    image: nginx
    restart: always
    ports:
      - 80:80
    networks:
      - domusnet
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
      - interface

networks:
  domusnet:

volumes:
  pgdata:
