version: '3'

services:
  database:
    build: ./database
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    networks:
      - mynetwork
    hostname: database

  api:
    build: ./web/API
    restart: always
    networks:
      - mynetwork
    depends_on:
      - database
    hostname: api

  webapp:
    image: mywebapp:latest
    restart: always
    ports:
      - 80:80
    networks:
      - mynetwork
    depends_on:
      - api
    hostname: webapp

networks:
  mynetwork:
